### ISSUE TITLE
Any Fully Working Language Switcher ?

### ISSUE THREAD

**Issue by scr4tchy** [schmittjoh/JMSI18nRoutingBundle#114]
Hello,

As the doc page is empty (after two years... ?). I searched & I saw some snippets of code but they're always some comments to say : it's not complete / correct ... etc.

So I'm asking: Where can I find a working snippet ?
By the way, I'm creating the language switcher with a drop down using KnpMenuBundle.

Thanks.

**Comment by JHGitty** [comment]
There is no working language switcher for slugs? :(

**Comment by migmolrod** [comment]
Not sure how much this can help:
https://gist.github.com/migmolrod/63be83ccbaf2a0db3fa4

It includes translatable locales. I mean, you can have a menu like this:
Deutsch
English
Español
日本人
Português

Which are:
German
English
Spanish
Japanese
Portuguese

That is, each locale in its own locale (pure common sense)

I think it's generic enough to be added in documentation.
But since KnpMenuBundle is so popular and OP mentioned it, maybe another gist with that approach could also perfeclty make its way to the I18nRoutingBundle docs.
