### ISSUE TITLE
security.yml -> access_control : %locale% in pattern ?

### ISSUE THREAD

**Issue by glecoz** [schmittjoh/JMSI18nRoutingBundle#39]
Hi, 

I'm using JMSI18nRoutingBundle for 3 languages : en, fr, es

In the access_control section of app/config/security.yml, I noticed that a path like **^/admin** isn't translated automatically as **^/fr/admin** or any defined language, unlike in app/config/routing.yml, so that **all the defined paths in access_control aren't catched (thus protected) by the firewall anymore (which leads to a main security issue)**.

The only way I found to circumvent this is to specify all the available languages for all paths, like this :

```
access_control:
        - { path: ^/(en|fr|es)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|es)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|es)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|es)/admin, role: ROLE_ADMIN }
```

But this is not very pleasant, if one have a more complex ACL or add another language, we have to add the new language in all paths.

As a feature in a further commit for JMSI18nRoutingBundle, could you please add the possibility to use the global var %locale% in the ACL paths, like this :

```
access_control:
        - { path: ^/%locale%/admin, role: ROLE_ADMIN }
```

Or maybe there's already a workaround for this, but I couldn't find any (_locale doesn't work either).

Thanks in advance.

**Comment by BenoitDuffez** [comment]
@schmittjoh I think it is partly related, unless I am wrong: I have a similar configuration on my access control:

```
access_control:
  - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
```

The access control is configured so that any URL is redirected to `fos_user_security_login`, that is `/login` in the code (which is in english). Now my default locale is French, and the URL is translated to `/connexion`.

The URL change works: if I do a curl on `/XYZ`, I get a 302 found with `Location: /connexion`.
This doesn't work with access control: if I do a curl on `/connexion`, I get a 302 found with `Location: /connexion`.
If I change the access control rule to `^/connexion$` it works.
So obviously this is not parsed properly.

Now I understand that AC is not for routes but for areas. However how can one achieve what I want, e.g. getting AC to play along with translated routes?
